image: docker

services:
  - docker:dind

stages:
  - build
  - test
  - deploy

before_script:
  - docker version
  - apk add --no-cache docker-compose
  - docker-compose version
  - docker login -u gitlab-ci-token -p $REGISTRY_TOKEN $REGISTRY

after_script:
  - docker-compose -f docker-compose.ci.yml down
  - docker-compose -f docker-compose.ci.yml ps


build:
  stage: build
  script:
    - echo "Building ..."
    - docker-compose -f docker-compose.ci.yml build
    - docker-compose -f docker-compose.ci.yml push

test:
  stage: test
  needs:
    - build
  script:
    - echo "Testing ..."
    - docker-compose -f docker-compose.ci.yml pull
    - docker-compose -f docker-compose.ci.yml run web sh -c "pipenv run python manage.py makemigrations && pipenv run python manage.py migrate && pipenv run python manage.py test core -v 2"

deploy:
  stage: deploy
  needs:
    - test
  script:
    - echo "Deploying ..."
    - pip install poetry
    - mw /the_social_network /not_needed
    - mw /core /the_social_network
    - poetry --version
    - poetry config pypi-token.pypi $POETRY_PYPI_TOKEN_PYPI
    - poetry publish