version: '3'

services:
  the_social_network:
    container_name: the_social_network
    build: ./social_network
    restart: always
    command: sh -c "poetry run python manage.py collectstatic --noinput && poetry run python manage.py runserver 0.0.0.0:9000"
    volumes:
      - ./social_network:/code
    networks:
      - webnet
    ports:
      - "9000:9000"
      
networks:
  webnet:
