[metadata]
name = the-social-network
version = 0.1
description = Basic core of all social network backends
long_description = file: README.rst
url = https://www.example.com/
author = Marc Feger
author_email = marc.feger@uni-duesseldorf.de
license = BSD-4-Clause
classifiers =
    Environment :: Web Environment
    Framework :: Django
    Framework :: Django :: 3.1.2  # Replace "X.Y" as appropriate
    Intended Audience :: Developers
    License :: OSI Approved :: BSD License
    Operating System :: OS Independent
    Programming Language :: Python
    Programming Language :: Python :: 3.9
    Topic :: Internet :: WWW/HTTP
    Topic :: Internet :: WWW/HTTP :: Dynamic Content

[options]
include_package_data = true
packages = find: